### ISSUE TITLE
目前有个需求要在此基础上加拖动和展开收起...

### ISSUE THREAD

**Issue by guoq1** [guaishouN/android-thinkmap-treeview#2]
大佬能加吗?

**Comment by guaishouN** [comment]
收起好弄。对子节点拖动，拖动添加节点还是拖动来移动节点？

**Comment by guoq1** [comment]
> 收起好弄。对子节点拖动，拖动添加节点还是拖动来移动节点？

http://platform.yingfeng365.top/page/testTree/newindex.html 仿这个, 右键选择第一个 vacate position

**Comment by guaishouN** [comment]
已经改好在main分支上
