### ISSUE TITLE
只有VerticalTreeLayoutManager与RightTreeLayoutManager两种布局

### ISSUE THREAD

**Issue by h79314711** [guaishouN/android-thinkmap-treeview#28]
implementation 'io.github.guaishoun:gyso-treeview:1.0.1'
只有VerticalTreeLayoutManager 和 RightTreeLayoutManager 两种布局方式

下载的里面却有好多种布局
RightTreeLayoutManager
LeftTreeLayoutManager
CompactRightTreeLayoutManager
CompactLeftTreeLayoutManager
…………………………

**Comment by guaishouN** [comment]
因为新增的布局还不稳定，所以没有添加到库里
