### ISSUE TITLE
数据无法保存

### ISSUE THREAD

**Issue by hardlove** [guaishouN/android-thinkmap-treeview#31]
请问数据改如何序列化成json数据存储起来呢？使用Gson序列化直接报错

**Comment by guaishouN** [comment]
这个问题在考虑要不要改，因为觉得这块功能超出了只做显示的初衷

**Comment by hardlove** [comment]
目前有没有什么方案可以把数据存储起来呢？毕竟用户辛辛苦苦的把导图创建好了，如果不能保持就没多大意义了

**Comment by hardlove** [comment]
改用fastjson来序列化没问题
val json = JSON.toJSONString(adapter.treeModel)
