### ISSUE TITLE
删除节点

### ISSUE THREAD

**Issue by MinDaren** [guaishouN/android-thinkmap-treeview#5]
请问怎么删除父节点下的所有子节点，同时不要删除父节点？现在项目里的代码是删除一个父节点后把子节点和当前节点都删了，所有我通过遍历每个子节点进行删除，但是在不使用删除节点动画时可以通过便利删除每个节点(虽然可以实现删除功能但是删除后视图会抖动偏移)，而当设置删除动画为true时节点会出现删不掉的bu g

**Comment by MinDaren** [comment]
好像是因为没有处理viewholder缓存的原因

**Comment by guaishouN** [comment]
我看看先，根据你需求尽快我再改改

**Comment by guaishouN** [comment]
> 请问怎么删除父节点下的所有子节点，同时不要删除父节点？现在项目里的代码是删除一个父节点后把子节点和当前节点都删了，所有我通过遍历每个子节点进行删除，但是在不使用删除节点动画时可以通过便利删除每个节点(虽然可以实现删除功能但是删除后视图会抖动偏移)，而当设置删除动画为true时节点会出现删不掉的bu g

问题已经修改好了, 使用'editor.removeNodeChildren(parentToRemoveChildren)'来通过父节点来删除子节点并保留父节点，开启删除动画吧，否则始终会有跳动的感觉

**Comment by MinDaren** [comment]
感觉大佬

发自闵浩的iPhone
