### ISSUE TITLE
只增加两个node时，line有长短，没有对齐

### ISSUE THREAD

**Issue by onexuan** [guaishouN/android-thinkmap-treeview#8]
treeModel.addNode(root,sub0,sub1);
只增加两个node时，line有长短，没有对齐

**Comment by guaishouN** [comment]
Hao de, wo zhao shi jian kan kan.  Dian nao shu ru fa huai le.

**Comment by guaishouN** [comment]
has fixed this problem

**Comment by guaishouN** [comment]
has fixed
